server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buybb?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  main:
    banner-mode: off
    allow-circular-references: true  #允许循环引用
  mvc:
    pathmatch:
      #?????swagger?
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:///Users/xjin1/IdeaProjects/mpbuybb/src/main/resources/images/,classpath:/static

  #????
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


file:
  upload:
    url: /Users/xjin1/IdeaProjects/buybb/src/main/resources/images


#mybatis-plus:



mybatis-plus:
#  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    banner:
      enabled: false
